name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: py${{ matrix.python-version }} on ${{ matrix.os }} with ${{ matrix.extras }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        os: [ubuntu-latest, windows-latest, macos-latest]
        extras: ["jax"]
        include:
          - python-version: "3.8"
            os: "ubuntu-latest"
            extras: "theano"
          - python-version: "3.8"
            os: "ubuntu-latest"
            extras: "theano-pymc jax"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install -e .[test]

      - name: Install starry and batman for comparisons on Linux
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.extras != 'theano-pymc' }}
        shell: bash -l {0}
        run: |
          python -m pip install "pymc3<3.10" theano==1.0.5
          python -m pip install starry batman-package

      - name: Install extras
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.extras != 'theano' }}
        shell: bash -l {0}
        run: |
          python -m pip install $EXTRAS
        env:
          EXTRAS: ${{ matrix.extras }}

      - name: Run tests
        shell: bash -l {0}
        run: python -m pytest -v tests
